# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gosh < Formula
  desc "CLI to list and access cloud instances"
  homepage "https://github.com/yogin/gosh"
  version "2.0.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/yogin/gosh/releases/download/v2.0.4/gosh_Darwin_arm64.tar.gz"
      sha256 "0f0bc6b2bfc026c1cd930d7ffcd99ee1a510453f9acba91f5ea01cfd2f317aa1"

      def install
        bin.install "gosh"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/yogin/gosh/releases/download/v2.0.4/gosh_Darwin_x86_64.tar.gz"
      sha256 "efb1de36fced1b2a5dec4964a073744888dcfd072a9acb3ef4a44b299117e619"

      def install
        bin.install "gosh"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/yogin/gosh/releases/download/v2.0.4/gosh_Linux_arm64.tar.gz"
      sha256 "aabb4a4f7c7c5cea9693ecc47a5f7f48fb91479b0b869dcb8063cfb0de9ffb7d"

      def install
        bin.install "gosh"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/yogin/gosh/releases/download/v2.0.4/gosh_Linux_x86_64.tar.gz"
      sha256 "8e90b7fc8c82d6fa06cb38cdf7b9e989fd20bc94189f07d34b40898b3306911a"

      def install
        bin.install "gosh"
      end
    end
  end
end
